### PR TITLE
Fix calculate top and left when using transform for parent element

### LINKED ISSUE #2: Calculate top and left when using transform for parent element
Keyboard will place on top/bottom of the element attached by `VKI_attach`.
It's almost all time is ok but for the following example I created in jsfiddle you can see it's position have problem.

[Sample of problem with css transform ](https://jsfiddle.net/sohrabi2050/ht3jb4pg/)

I try to fix it by using `getBoundingClientRect` in `VKI_findPos` method, but it's not fixed my problem.
https://github.com/GreyWyvern/virtual-keyboard/blob/979d641beebce2f05bd20a75f6a9238e15b776c1/keyboard.js#L1831

I will appreciate if you could help me handle it.

### PR DESCRIPTION
**Pull request by sohrabi**
It's a fix for this bug:

fix https://github.com/GreyWyvern/virtual-keyboard/issues/2

### CODE REVIEW

**Comment by GreyWyvern** [comment]
Thanks for this!

Your PR switches the default `position` CSS style of the keyboard to `fixed` which I'm not a fan of. Most of the rest of the PR is compensating for this change, when the key fix for the issue can be isolated in the `VKI_findPos()` function.

If the current input has a fixed position parent, then use `getBoundingClientRect()`, and if not, use the old `VKI_findPos()` code.

```javascript
  function VKI_findPos(obj) {
    if (self.VKI_target.keyboardPosition != 'fixed') {
      let curleft = curtop = 0, scr = obj;
      while ((scr = scr.parentNode) && scr != document.body) {
        curleft -= scr.scrollLeft || 0;
        curtop -= scr.scrollTop || 0;
      }
      do {
        curleft += obj.offsetLeft;
        curtop += obj.offsetTop;
      } while (obj = obj.offsetParent);
      return [curleft, curtop];
    } else {
      let boundingRect = obj.getBoundingClientRect();
      return [boundingRect.left, boundingRect.top];
    }
  }
```

Let me know if just the change above fixes your issue.

**Comment by sohrabi** [comment]
Thanks,

I check it. it will not solve problem for all probable input positions.
So I undo almost all changes and add some clause for 'fixed' parent elements.
I commit changes again, while I use the codes on your comment.

I hope this have no side effects on keyboards used currently.

**Comment by GreyWyvern** [comment]
Thanks! Are you able to prepare some example page where the changes you've made fix the "all probable input positions" positioning issues outside of the changes I suggested to VKI_findPos?

**Comment by sohrabi** [comment]
Your welcome, I just pushed a test page for this purpose.

**Comment by GreyWyvern** [comment]
> Your welcome, I just pushed a test page for this purpose.

Your test page works for me (the keyboard lines up properly with the center text fields) with only the changes from line 1840 to 1853 (just `VKI_findPos()`). The other changes don't appear to be necessary, unless I'm missing something in your test page?

**Comment by sohrabi** [comment]
I have created some other test with this change in js code only and it seems to work fine:
```
  function VKI_findPos(obj) {
    if (self.VKI_target.keyboardPosition != 'fixed') {
      let curleft = curtop = 0, scr = obj;
      while ((scr = scr.parentNode) && scr != document.body) {
        curleft -= scr.scrollLeft || 0;
        curtop -= scr.scrollTop || 0;
      }
      do {
        curleft += obj.offsetLeft;
        curtop += obj.offsetTop;
      } while (obj = obj.offsetParent);
      return [curleft, curtop];
    } else {
      let boundingRect = obj.getBoundingClientRect();
      return [boundingRect.left, boundingRect.top];
    }
  }
  ````
  
I have undo all my changes and just apply this into code , if you like you can accept this pull request or simply apply changes by yourself and ignore this PR.

**Pull request closed without merging**
